Predicting an individual player's stats against a given opponent, giving over/unders for theoretical gambling game

In [16]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [53]:
df = pd.read_csv('../Data/player_stats3.csv')

In [54]:
df.head()

,patch,date,name,map,team,opponent,agent,kills,deaths,assists,acs,acs_attack,acs_defense,kast,first_kills,first_deaths,headshot_pct,map_url
0,Patch 11.0,2025/08/16,adverso,Corrode,FURIA,Evil Geniuses,Fade,13,15,8,209.0,158.0,239.0,68.0,2,0,19.0,https://www.vlr.gg/509827/furia-vs-evil-genius...
1,Patch 11.0,2025/08/16,Palla,Corrode,FURIA,Evil Geniuses,Neon,14,16,5,212.0,289.0,167.0,63.0,3,7,35.0,https://www.vlr.gg/509827/furia-vs-evil-genius...
2,Patch 11.0,2025/08/16,Urango,Corrode,FURIA,Evil Geniuses,Sage,13,17,6,189.0,213.0,176.0,74.0,0,3,48.0,https://www.vlr.gg/509827/furia-vs-evil-genius...
3,Patch 11.0,2025/08/16,tuyz,Corrode,FURIA,Evil Geniuses,Omen,10,17,4,154.0,185.0,137.0,53.0,0,0,21.0,https://www.vlr.gg/509827/furia-vs-evil-genius...
4,Patch 11.0,2025/08/16,heat,Corrode,FURIA,Evil Geniuses,Viper,4,18,3,63.0,48.0,72.0,42.0,1,3,31.0,https://www.vlr.gg/509827/furia-vs-evil-genius...

In [55]:
# Load valid teams and filter dataframe
with open('../Data/Dictionaries/team_names.txt', encoding='utf-8') as f:
    valid_teams = set(line.strip() for line in f if line.strip())

df = df[df['team'].isin(valid_teams) & df['opponent'].isin(valid_teams)]

In [56]:
df = df[(df['kills'] != 0) | (df['deaths'] != 0) | (df['assists'] != 0)]

In [57]:
df.head()

,patch,date,name,map,team,opponent,agent,kills,deaths,assists,acs,acs_attack,acs_defense,kast,first_kills,first_deaths,headshot_pct,map_url
0,Patch 11.0,2025/08/16,adverso,Corrode,FURIA,Evil Geniuses,Fade,13,15,8,209.0,158.0,239.0,68.0,2,0,19.0,https://www.vlr.gg/509827/furia-vs-evil-genius...
1,Patch 11.0,2025/08/16,Palla,Corrode,FURIA,Evil Geniuses,Neon,14,16,5,212.0,289.0,167.0,63.0,3,7,35.0,https://www.vlr.gg/509827/furia-vs-evil-genius...
2,Patch 11.0,2025/08/16,Urango,Corrode,FURIA,Evil Geniuses,Sage,13,17,6,189.0,213.0,176.0,74.0,0,3,48.0,https://www.vlr.gg/509827/furia-vs-evil-genius...
3,Patch 11.0,2025/08/16,tuyz,Corrode,FURIA,Evil Geniuses,Omen,10,17,4,154.0,185.0,137.0,53.0,0,0,21.0,https://www.vlr.gg/509827/furia-vs-evil-genius...
4,Patch 11.0,2025/08/16,heat,Corrode,FURIA,Evil Geniuses,Viper,4,18,3,63.0,48.0,72.0,42.0,1,3,31.0,https://www.vlr.gg/509827/furia-vs-evil-genius...

In [58]:
df['kda'] = (df['kills'] + df['assists']) / df['deaths'].replace(0, 1)
df['kd'] = df['kills'] / df['deaths'].replace(0, 1)

In [59]:
max_kda_row = df.loc[df['kda'].idxmax()]
print(max_kda_row)

patch                                                 Patch 11.05
date                                                   2025/09/26
name                                                        brawk
map                                                         Haven
team                                                          NRG
opponent                                                   GIANTX
agent                                                        Sova
kills                                                          18
deaths                                                          1
assists                                                         8
acs                                                         324.0
acs_attack                                                  298.0
acs_defense                                                 486.0
kast                                                         93.0
first_kills                                                     1
first_deaths                                                    0
headshot_pct                                                 15.0
map_url         https://www.vlr.gg/542267/nrg-vs-giantx-valora...
kda                                                          26.0
kd                                                           18.0
Name: 9850, dtype: object

In [ ]:
max_kills_row = df.loc[df[''].idxmin()]
print(max_kills_row)

patch                                                 Patch 11.05
date                                                   2025/09/26
name                                                        brawk
map                                                         Haven
team                                                          NRG
opponent                                                   GIANTX
agent                                                        Sova
kills                                                          18
deaths                                                          1
assists                                                         8
acs                                                         324.0
acs_attack                                                  298.0
acs_defense                                                 486.0
kast                                                         93.0
first_kills                                                     1
first_deaths                                                    0
headshot_pct                                                 15.0
map_url         https://www.vlr.gg/542267/nrg-vs-giantx-valora...
kda                                                          26.0
kd                                                           18.0
Name: 9850, dtype: object